### ISSUE TITLE
DeltaEcore update site not available

### ISSUE THREAD

**Issue by lschuetze** [Eden-06/RoSI_CROM#1]
The installation instruction says to install DeltaEcore from http://www.deltaecore.org/update but this URI respond with error 404. The site is no more available.

**Comment by lschuetze** [comment]
The update site is hosted at the Technische Universität Dresden whose firewall blocks all traffic currently. It should be reachable from within the university network (e.g., eduroam)

**Comment by Eden-06** [comment]
The update site has been moved to another location on another server outside the firewall of the Technische Universität Dresden. Could you check the update site again?
- [http://www.deltaecore.org/update](http://www.deltaecore.org/update)

**Comment by Eden-06** [comment]
I checked the update site myself.
